### ISSUE TITLE
你好，这个项目打包传到集群上运行，不能运行

### ISSUE THREAD

**Issue by ytousxljsj** [oeljeklaus-you/UserActionAnalyzePlatform#4]
Exception in thread "main" java.lang.NullPointerException
        at cn.edu.hust.util.ParamUtils.getParam(ParamUtils.java:35)
        at cn.edu.hust.session.UserVisitAnalyze.getActionRDD(UserVisitAnalyze.java:155)
        at cn.edu.hust.session.UserVisitAnalyze.main(UserVisitAnalyze.java:58)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:730)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by oeljeklaus-you** [comment]
是否首先产生了模拟数据

**Comment by qiaoxiaoqiao0605** [comment]
模拟数据也产生了，task表是空的是什么原因啊

**Comment by wanquanchen** [comment]
怎样产生模拟数据啊？没有看到
